FROM python
RUN git clone -q https://github.com/lcorralesg/Alexa-django.git
WORKDIR /Alexa-django
RUN pip install -r requirements.txt
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen es_ES.UTF-8
CMD ["python", "manage.py", "runserver", "0:80"]
EXPOSE 80