FROM python
RUN git clone -q https://github.com/lcorralesg/alexa_docs.git
WORKDIR /alexa_docs
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]